# Generated by Django 5.2.7 on 2025-10-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={"verbose_name": "дом", "verbose_name_plural": "дома"},
        ),
    ]
