# Generated by Django 5.2.7 on 2025-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_alter_house_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": ["name"],
                "verbose_name": "дом",
                "verbose_name_plural": "дома",
            },
        ),
        migrations.AddField(
            model_name="house",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="houses/photos",
                verbose_name="фотография",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=50, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.IntegerField(verbose_name="цена"),
        ),
    ]
