# Generated by Django 5.2.7 on 2025-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_house_options_house_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
