# Generated by Django 5.2.7 on 2025-10-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("houses", "0003_alter_house_options_house_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя")),
                ("phone", models.CharField(max_length=50, verbose_name="телефон")),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="дата")),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="houses.house",
                        verbose_name="дом",
                    ),
                ),
            ],
        ),
    ]
