# Generated by Django 5.2.7 on 2025-10-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_house_options_house_photo_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
    ]
