# Generated by Django 5.2.7 on 2025-10-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_orders_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="data",
            new_name="date",
        ),
    ]
